### ISSUE TITLE
Project Improvement

### ISSUE THREAD

**Issue by miguelpimentel** [Escola-em-Casa/ios-escola-em-casa#1]
Good Evening, I've noticed some good points to improvement. They are presented below:

* Wikipedia (Apply SearchController and Wikipedia API)
* Some constraints errors
* Visual components structure(Storyboard, xib and view code)
* Architecture (MVP,  VIP, VIPER)
* CI (SwiftLint + Danger) - Github Actions
* UI Improvements

**Comment by laercios** [comment]
Hi @miguelpimentel, how are you doing ?

These are good points to improve. 

I will comment about the points:

- Wikipedia (Apply SearchController and Wikipedia API) 

This is nice feature, today the wikipedia is opened inside of web view. Implement a Search Screen through Wikipedia API looks nice. But implementation on android app might be necessary as well, in order to keep consistency between both apps.

- UI Improvements & Some constraints errors

I've tested the user interface with many devices, and it works well. But I know it can be improved. I usually have tested with iPhone 11 and iPhone SE 1 ( this phone has the smallest screen which the application will run).

iPhone SE 1 has the same screen that iPhone 5S, the oldest phone that can be run this application. This is important thing, is a requirement of this project, because not all students have I new phone.  We will need to have sure that run fine until 4 inch screens.


- CI (SwiftLint + Danger) - Github Actions
This is a great thing. 

- Visual components structure(Storyboard, xib and view code)
This can be improved, but idk how. How you will improve this ? 

- Architecture (MVP, VIP, VIPER)
Which one will you suggest to use for this project ? 

Did you see the branch "reverseBill" ? This branch has datami SDK and it has more code than branch master. 


--------


If you would like to test reverse bill feature or if you had some doubt or need help for understand something about the project, just send me a Telegram message.

Best Regards,
Laércio S.
